development:
  adapter: postgresql
  encoding: latin1
  database: pingpong_test_development
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

test:
  adapter: postgresql
  encoding: latin1
  database: pingpong_test_test
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000